# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-10 20:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Workflow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_peripheral', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='from_peripheral', to='api.Peripheral')),
                ('from_service', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='from_service', to='api.Service')),
                ('from_service_number', models.IntegerField()),
                ('from_value', models.CharField(max_length=500)),
                ('to_peripheral', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='to_peripheral', to='api.Peripheral')),
                ('to_service', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='to_service', to='api.Service')),
                ('to_service_number', models.IntegerField()),
                ('to_value', models.CharField(max_length=500)),
            ],
        ),
    ]
