# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-11-30 03:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='peripheralservice',
            name='service_name',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
